version: '3'

services:
  db:
    image: postgres
    restart: always
    networks:
      - app-network
    volumes:
      - ./database:/var/lib/postgresql/data
  app:
    build: .
    command: yarn start:dev
    networks:
      - app-network
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
    networks:
      - app-network
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - '9092:9092'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
